---
# This playbook contains common plays that will be run on all nodes.
#- name: add yum nginx repo
#  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx 
  #yum: name=nginx state=present
  apt: name=nginx state=present

- name: Install git
  apt: name={{ item }} state=present
  with_items:
    - git

- name: Start the nginx service
  service: name=nginx state=started enabled=yes
